// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2Rf-LaaMk1TSdrlMiI8UPOU3yiXDVZo',
    appId: '1:524499434204:android:e2d4cfc6f1751b30dd1219',
    messagingSenderId: '524499434204',
    projectId: 'blocphotoapp',
    storageBucket: 'blocphotoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rkqFc-K0resbJVQUqT9IV8hoS28OkSA',
    appId: '1:524499434204:ios:c6632656d1ca5813dd1219',
    messagingSenderId: '524499434204',
    projectId: 'blocphotoapp',
    storageBucket: 'blocphotoapp.appspot.com',
    iosClientId: '524499434204-5967t7t5lrbk1ipkv3cnbue4c9tn1o5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocExamples',
  );
}
